services:
  cathub-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cathub-backend
    restart: always
    ports:
      - "1111:3333"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production