services:
  mongo:
    image: mongo:7.0.18
    container_name: mongo
    hostname: www.atenasoficial.com   # 🔹 clave para que Mongo se detecte así
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    extra_hosts:
      - "www.atenasoficial.com:${PRIVATE_IP}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "${MONGO_PORT}", "--keyFile", "/data/configdb/mongodb-keyfile"]
    volumes:
      - mongo-data:/data/db
      - ./keyfile:/data/configdb
    networks:
      - igmar-net

  postgres:
    image: postgres:17.5
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - igmar-net

  cathub:
    build: .
    ports:
      - "${API_PORT}:3333"
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
      APP_KEY: 7Otq2phcA_g__DtX_NQLJZRQN7jxIdFa
      TZ: UTC
      PORT: 3333
      HOST: 0.0.0.0
      NODE_ENV: development
      DB_CONNECTION: pg
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      DB_HOST: postgres
      DB_PORT: 5432
      MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWOR}D@mongo:27017/${MONGO_DB}?authSource=admin
    volumes:
      - ./:/app
    networks:
      - igmar-net

networks:
  igmar-net:
    external: true
    driver: bridge


volumes:
  mongo-data:
  postgres-data:
