services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "1100:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: db_cathub  
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro  # Scripts de inicialización

volumes:
  mongo-data: